# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty    

# Setup
title:            'Thy Mai'
tagline:          'Resume'    
description:      'Computer Science student at Southern Illinois University Edwardsville'   
url:              https://thym101.github.io     
baseurl:          /       

author:
  name:           'Thy Mai'
  url:            www.linkedin.com/in/thy-mai-66838b291   


paginate:         5  

# Custom vars
version:          2.1.0     

github:
  repo:           https://github.com/thym101/thym101.github.io   
